namespace CodeMap.Roslyn.Extraction;

using System.Diagnostics;
using CodeMap.Core.Interfaces;
using CodeMap.Core.Types;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.Extensions.Logging;
using CodeMapRefKind = CodeMap.Core.Enums.RefKind;

/// <summary>
/// Walks a Roslyn Compilation and extracts all inter-symbol references.
/// </summary>
internal static class ReferenceExtractor
{
    public static IReadOnlyList<ExtractedReference> ExtractAll(
        Compilation compilation,
        string solutionDir,
        IReadOnlyDictionary<string, StableId>? stableIdMap = null,
        IReadOnlySet<string>? crossProjectSymbolIds = null,
        ILogger? logger = null,
        IReadOnlySet<string>? includedAbsolutePaths = null)
    {
        var references = new List<ExtractedReference>();

        // T2c: per-symbol cache for IsSourceSymbol so cross-project doc-id
        // resolution amortizes within a single ExtractAll run.
        var isSourceCache = new Dictionary<ISymbol, bool>(SymbolEqualityComparer.Default);

        // T1 instrumentation kept (LogInformation, low-overhead). Lets us
        // verify post-fix that classify_ms drops to its expected ratio.
        long classifyTicks = 0, isSourceTicks = 0, findContainingTicks = 0,
             getSymbolIdTicks = 0, locationTicks = 0, descendTicks = 0;
        int treeCount = 0, nodeCount = 0, classifiedCount = 0,
            crossProjectHits = 0, refsAdded = 0, skippedTrees = 0;
        long worstTreeMs = 0;
        string? worstTreePath = null;

        foreach (var tree in compilation.SyntaxTrees)
        {
            if (!ExtractionScope.Includes(tree, includedAbsolutePaths))
                continue;
            // T2a: skip auto-generated trees. Path heuristics + leading-trivia
            // <auto-generated> sniff. Catches GlobalUsings.g.cs, *.Designer.cs,
            // anything under obj/, and explicit auto-gen markers.
            if (IsGeneratedFile(tree))
            {
                skippedTrees++;
                continue;
            }

            treeCount++;
            var swTree = Stopwatch.StartNew();
            var model = compilation.GetSemanticModel(tree);
            var root = tree.GetRoot();

            var swDescend = Stopwatch.StartNew();
            var nodes = root.DescendantNodes().ToList();
            swDescend.Stop();
            descendTicks += swDescend.ElapsedTicks;
            nodeCount += nodes.Count;

            foreach (var node in nodes)
            {
                var sw1 = Stopwatch.StartNew();
                var classified = RefKindClassifier.TryClassify(node, model);
                sw1.Stop();
                classifyTicks += sw1.ElapsedTicks;
                if (classified is null) continue;
                classifiedCount++;

                var (targetSymbol, refKind) = classified.Value;

                var sw2 = Stopwatch.StartNew();
                bool isSource = IsSourceSymbolCached(targetSymbol, compilation, crossProjectSymbolIds, isSourceCache);
                sw2.Stop();
                isSourceTicks += sw2.ElapsedTicks;
                if (!isSource) continue;
                if (!SymbolEqualityComparer.Default.Equals(targetSymbol.ContainingAssembly, compilation.Assembly))
                    crossProjectHits++;

                var sw3 = Stopwatch.StartNew();
                var fromSymbol = FindContainingSymbol(node, model);
                sw3.Stop();
                findContainingTicks += sw3.ElapsedTicks;
                if (fromSymbol is null) continue;

                var sw4 = Stopwatch.StartNew();
                var fromId = GetSymbolId(fromSymbol);
                var toId = GetSymbolId(targetSymbol);
                sw4.Stop();
                getSymbolIdTicks += sw4.ElapsedTicks;
                if (fromId is null || toId is null) continue;

                var sw5 = Stopwatch.StartNew();
                var location = node.GetLocation();
                var filePathN = GetFilePath(location, solutionDir);
                sw5.Stop();
                locationTicks += sw5.ElapsedTicks;
                if (filePathN is null) continue;

                var lineSpan = location.GetLineSpan();
                int lineStart = lineSpan.StartLinePosition.Line + 1;
                int lineEnd = lineSpan.EndLinePosition.Line + 1;

                StableId? stableFrom = stableIdMap?.TryGetValue(fromId, out var sfid) == true ? sfid : null;
                StableId? stableTo = stableIdMap?.TryGetValue(toId, out var stid) == true ? stid : null;

                references.Add(new ExtractedReference(
                    FromSymbol: SymbolId.From(fromId),
                    ToSymbol: SymbolId.From(toId),
                    Kind: refKind,
                    FilePath: filePathN.Value,
                    LineStart: lineStart,
                    LineEnd: lineEnd,
                    StableFromId: stableFrom,
                    StableToId: stableTo
                ));
                refsAdded++;
            }

            swTree.Stop();
            if (swTree.ElapsedMilliseconds > worstTreeMs)
            {
                worstTreeMs = swTree.ElapsedMilliseconds;
                worstTreePath = tree.FilePath;
            }
        }

        // Walk declarations for Override and Implementation relationships
        ExtractDeclarationRelationships(compilation, references, solutionDir, stableIdMap,
            crossProjectSymbolIds, includedAbsolutePaths);

        if (logger is not null)
        {
            static long TicksToMs(long t) => t * 1000 / Stopwatch.Frequency;
            logger.LogInformation(
                "PHASE_TIMING_REFS_INNER assembly={Assembly} trees={Trees} skipped_trees={Skipped} nodes={Nodes} classified={Classified} cross_hits={CrossHits} refs_added={Refs} " +
                "descend_ms={DescendMs} classify_ms={ClassifyMs} is_source_ms={IsSourceMs} find_containing_ms={FindContMs} get_symbol_id_ms={GetIdMs} location_ms={LocMs} " +
                "worst_tree_ms={WorstMs} worst_tree_path={WorstPath}",
                compilation.AssemblyName ?? "?", treeCount, skippedTrees, nodeCount, classifiedCount, crossProjectHits, refsAdded,
                TicksToMs(descendTicks), TicksToMs(classifyTicks), TicksToMs(isSourceTicks),
                TicksToMs(findContainingTicks), TicksToMs(getSymbolIdTicks), TicksToMs(locationTicks),
                worstTreeMs, worstTreePath ?? "?");
        }

        return references;
    }

    /// <summary>
    /// T2a: detect auto-generated source files we can skip. Combines path
    /// heuristics (.g.cs, .Designer.cs, .Generated.cs, .AssemblyInfo.cs,
    /// anything under obj/) with the standard <c>&lt;auto-generated&gt;</c>
    /// leading-comment marker. Public for testability.
    /// </summary>
    internal static bool IsGeneratedFile(SyntaxTree tree)
    {
        var path = tree.FilePath ?? "";
        if (path.Length > 0)
        {
            var fileName = Path.GetFileName(path);
            if (fileName.EndsWith(".g.cs", StringComparison.OrdinalIgnoreCase) ||
                fileName.EndsWith(".g.i.cs", StringComparison.OrdinalIgnoreCase) ||
                fileName.EndsWith(".Generated.cs", StringComparison.OrdinalIgnoreCase) ||
                fileName.EndsWith(".Designer.cs", StringComparison.OrdinalIgnoreCase) ||
                fileName.EndsWith(".AssemblyInfo.cs", StringComparison.OrdinalIgnoreCase) ||
                fileName.Equals("AssemblyInfo.cs", StringComparison.OrdinalIgnoreCase) ||
                fileName.Equals("AssemblyAttributes.cs", StringComparison.OrdinalIgnoreCase) ||
                fileName.Equals("GlobalUsings.g.cs", StringComparison.OrdinalIgnoreCase))
                return true;

            var normalized = path.Replace('\\', '/');
            if (normalized.Contains("/obj/", StringComparison.OrdinalIgnoreCase))
                return true;
        }

        // Sniff for the standard <auto-generated> marker in the leading
        // comment block of the file. Only check up to a small prefix —
        // genuine auto-gen tools place it at the top.
        var root = tree.GetRoot();
        var leading = root.GetLeadingTrivia();
        int seen = 0;
        foreach (var trivia in leading)
        {
            if (trivia.IsKind(SyntaxKind.SingleLineCommentTrivia) ||
                trivia.IsKind(SyntaxKind.MultiLineCommentTrivia) ||
                trivia.IsKind(SyntaxKind.SingleLineDocumentationCommentTrivia) ||
                trivia.IsKind(SyntaxKind.MultiLineDocumentationCommentTrivia))
            {
                var text = trivia.ToString();
                if (text.Contains("<auto-generated", StringComparison.OrdinalIgnoreCase))
                    return true;
                if (++seen > 8) break;
            }
        }
        return false;
    }

    /// <summary>
    /// T2c: cached IsSourceSymbol. Eliminates repeated
    /// <c>GetDocumentationCommentId</c> calls for the same symbol within
    /// one ExtractAll run.
    /// </summary>
    private static bool IsSourceSymbolCached(
        ISymbol symbol, Compilation compilation,
        IReadOnlySet<string>? crossProjectSymbolIds,
        Dictionary<ISymbol, bool> cache)
    {
        if (cache.TryGetValue(symbol, out var cached)) return cached;
        var result = IsSourceSymbol(symbol, compilation, crossProjectSymbolIds);
        cache[symbol] = result;
        return result;
    }

    private static void ExtractDeclarationRelationships(Compilation compilation,
        List<ExtractedReference> references,
        string solutionDir,
        IReadOnlyDictionary<string, StableId>? stableIdMap,
        IReadOnlySet<string>? crossProjectSymbolIds = null,
        IReadOnlySet<string>? includedAbsolutePaths = null)
    {
        foreach (var type in GetAllSourceTypes(compilation)
            .Where(type => type.Locations.Any(location =>
                ExtractionScope.Includes(location.SourceTree, includedAbsolutePaths))))
        {
            foreach (var member in type.GetMembers())
            {
                if (member is IMethodSymbol method)
                {
                    // Override relationship
                    if (method.IsOverride && method.OverriddenMethod is { } overridden
                        && IsSourceSymbol(overridden, compilation, crossProjectSymbolIds))
                    {
                        AddDeclRef(method, overridden, CodeMapRefKind.Override, references, solutionDir, stableIdMap);
                    }

                    // Interface implementation relationships
                    foreach (var iface in type.AllInterfaces)
                    {
                        foreach (var ifaceMember in iface.GetMembers().OfType<IMethodSymbol>())
                        {
                            var impl = type.FindImplementationForInterfaceMember(ifaceMember);
                            if (impl is IMethodSymbol implMethod &&
                                SymbolEqualityComparer.Default.Equals(implMethod, method))
                            {
                                AddDeclRef(method, ifaceMember, CodeMapRefKind.Implementation, references, solutionDir, stableIdMap);
                            }
                        }
                    }
                }
            }
        }
    }

    private static void AddDeclRef(IMethodSymbol from, IMethodSymbol to,
        CodeMapRefKind kind, List<ExtractedReference> references,
        string solutionDir, IReadOnlyDictionary<string, StableId>? stableIdMap)
    {
        var fromId = GetSymbolId(from);
        var toId = GetSymbolId(to);
        if (fromId is null || toId is null) return;

        var loc = from.Locations.FirstOrDefault(l => l.IsInSource);
        var fpN = loc is not null ? GetFilePath(loc, solutionDir) : null;
        if (fpN is null) return;

        StableId? stableFrom = stableIdMap?.TryGetValue(fromId, out var sfid) == true ? sfid : null;
        StableId? stableTo = stableIdMap?.TryGetValue(toId, out var stid) == true ? stid : null;

        var ls = loc!.GetLineSpan();
        references.Add(new ExtractedReference(
            SymbolId.From(fromId), SymbolId.From(toId),
            kind, fpN.Value,
            ls.StartLinePosition.Line + 1,
            ls.EndLinePosition.Line + 1,
            StableFromId: stableFrom,
            StableToId: stableTo));
    }

    private static ISymbol? FindContainingSymbol(SyntaxNode node, SemanticModel model)
    {
        // Use language-agnostic GetDeclaredSymbol — works for both C# and VB.NET.
        var current = node.Parent;
        while (current is not null)
        {
            var declared = model.GetDeclaredSymbol(current);
            if (declared is IMethodSymbol or IPropertySymbol)
                return declared;
            current = current.Parent;
        }

        // Fallback: find containing type
        current = node.Parent;
        while (current is not null)
        {
            var declared = model.GetDeclaredSymbol(current);
            if (declared is INamedTypeSymbol)
                return declared;
            current = current.Parent;
        }

        return null;
    }

    private static bool IsSourceSymbol(ISymbol symbol, Compilation compilation,
        IReadOnlySet<string>? crossProjectSymbolIds = null)
    {
        // Accept symbols from the same assembly (intra-project refs)
        if (SymbolEqualityComparer.Default.Equals(symbol.ContainingAssembly, compilation.Assembly))
            return true;
        // Accept symbols from same-language referenced projects (CompilationReference — source locations preserved).
        // Framework symbols (System.*, Microsoft.*) have no source locations so this excludes them.
        if (symbol.Locations.Any(l => l.IsInSource))
            return true;
        // Accept symbols from cross-language referenced projects (MetadataReference — no source locations).
        // Roslyn compiles C# projects to DLL before referencing from VB (and vice-versa), so source
        // locations are absent. We fall back to doc-comment ID lookup against the known symbol set
        // built from all projects in the solution that were processed before this one.
        if (crossProjectSymbolIds is not null)
        {
            var docId = symbol.GetDocumentationCommentId();
            if (docId is not null && crossProjectSymbolIds.Contains(docId))
                return true;
        }
        return false;
    }

    private static IEnumerable<INamedTypeSymbol> GetAllSourceTypes(Compilation compilation) =>
        GetTypesFromNamespace(compilation.Assembly.GlobalNamespace);

    private static IEnumerable<INamedTypeSymbol> GetTypesFromNamespace(INamespaceSymbol ns)
    {
        foreach (var member in ns.GetMembers())
        {
            if (member is INamespaceSymbol childNs)
                foreach (var t in GetTypesFromNamespace(childNs))
                    yield return t;
            else if (member is INamedTypeSymbol type)
                yield return type;
        }
    }

    private static string? GetSymbolId(ISymbol symbol) =>
        symbol.GetDocumentationCommentId()
        ?? symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

    private static FilePath? GetFilePath(Location location, string solutionDir)
    {
        if (!location.IsInSource || location.SourceTree is null) return null;
        return ExtractionScope.ToRepositoryPath(solutionDir, location.SourceTree.FilePath);
    }
}
